### ISSUE TITLE
[Bug]: Plugin does not appear to handle a condition where the Porkbun DNS record has multiple TXT _acme-challenge.example.com entries

### ISSUE THREAD

**Issue by smclewin** [infinityofspace/certbot_dns_porkbun#98]
### OS info

I am using the infinityofspace/certbot_dns_porkbun container

### Docker image

- [X] I am using the docker image.

### certbot_dns_porkbun version

0.9.1, latest pulled in the infinityofspace/certbot_dns_porkbun container

### certbot version

3.0.1, latest pulled from the infinityofspace/certbot_dns_porkbun container

### Bug description

In setting up the _infinityofspace/certbot_dns_porkbun_ container to run on a schedule to renew my wildcard cert I appear to have created a condition where my domain had four _acme-challenge TXT records in Porkbun's DNS.  Likely a side effect of whatever exploration I was doing to get certbot working.

At some point in my efforts I started getting errors from the plug-in

> certbot.errors.PluginError: ERROR: Create error: We were unable to create the DNS record.
> 
> 2024-12-28 16:46:41,678:DEBUG:certbot._internal.error_handler:Calling registered functions
> 2024-12-28 16:46:41,678:INFO:certbot._internal.auth_handler:Cleaning up challenges
> 2024-12-28 16:46:41,679:ERROR:certbot._internal.error_handler:Encountered exception during recovery: KeyError: 'L6ZhfQAySh3-c_I8gH3wqLgtPEXNxj2oTNSpOmq66-w'
> 2024-12-28 16:46:41,679:DEBUG:certbot._internal.log:Exiting abnormally:

In looking at the client.py code the conclusion I came to - which may be incorrect - is that it is assuming there is a single TXT record named _acme-challenge.example.com and not an array of them.

I don't know how I got the DNS entry at Porkbun into this state.  I've attached a sanitized version of the log for one of the failed sessions.

Once I manually deleted every existing _acme-challenge TXT record this error condition went away.

[letsencrypt-multiple-txt-acme-challenge-fail.log](https://github.com/user-attachments/files/18267008/letsencrypt-multiple-txt-acme-challenge-fail.log)

### Expected behaviour description

I suspect any (all) old TXT _acme-challenge records should be deleted as part of the _cleanup method being called on the plug-in from certbot.

### Relevant log output

```shell
2024-12-28 16:46:40,115:DEBUG:certbot._internal.main:certbot version: 3.0.1
2024-12-28 16:46:40,115:DEBUG:certbot._internal.main:Location of certbot entry point: /opt/venv/bin/certbot
2024-12-28 16:46:40,115:DEBUG:certbot._internal.main:Arguments: ['-v', '--non-interactive', '--agree-tos', '--email', 'REMOVED', '--preferred-challenges', 'dns', '--authenticator', 'dns-porkbun', '--dns-porkbun-key', 'REMOVED', '--dns-porkbun-secret', 'REMOVED', '--dns-porkbun-propagation-seconds', '600', '-d', '*.example.com']
2024-12-28 16:46:40,115:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#dns-porkbun,PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2024-12-28 16:46:40,193:DEBUG:certbot._internal.log:Root logging level set at 20
2024-12-28 16:46:40,195:DEBUG:certbot._internal.plugins.selection:Requested authenticator dns-porkbun and installer None
2024-12-28 16:46:40,195:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * dns-porkbun
Description: Obtain certificates using a DNS TXT record for Porkbun domains
Interfaces: Authenticator, Plugin
Entry point: EntryPoint(name='dns-porkbun', value='certbot_dns_porkbun.cert.client:Authenticator', group='certbot.plugins')
Initialized: <certbot_dns_porkbun.cert.client.Authenticator object at 0xffffb150c590>
Prep: True
2024-12-28 16:46:40,195:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot_dns_porkbun.cert.client.Authenticator object at 0xffffb150c590> and installer None
2024-12-28 16:46:40,195:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator dns-porkbun, Installer None
2024-12-28 16:46:40,235:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/REMOVED', new_authzr_uri=None, terms_of_service=None), REMOVED, Meta(creation_dt=datetime.datetime(2024, 12, 28, 3, 29, 7, tzinfo=datetime.timezone.utc), creation_host='REMOVED', register_to_eff=None))>
2024-12-28 16:46:40,235:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2024-12-28 16:46:40,238:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2024-12-28 16:46:40,362:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "GET /directory HTTP/11" 200 746
2024-12-28 16:46:40,363:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 28 Dec 2024 16:46:40 GMT
Content-Type: application/json
Content-Length: 746
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "SsCLLlTvpYM": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/REMOVED",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.4-April-3-2024.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "renewalInfo": "https://acme-v02.api.letsencrypt.org/draft-ietf-acme-ari-03/renewalInfo",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
}
2024-12-28 16:46:40,365:DEBUG:certbot._internal.display.obj:Notifying user: Requesting a certificate for *.example.com
2024-12-28 16:46:40,369:DEBUG:acme.client:Requesting fresh nonce
2024-12-28 16:46:40,369:DEBUG:acme.client:Sending HEAD request to https://acme-v02.api.letsencrypt.org/acme/new-nonce.
2024-12-28 16:46:40,408:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "HEAD /acme/new-nonce HTTP/11" 200 0
2024-12-28 16:46:40,408:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 28 Dec 2024 16:46:40 GMT
Connection: keep-alive
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: LPSR-4-sJ5XwJ_v92mKoIo-p7Y0KyU4levWDDWoyVYbCqvku0rQ
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800


2024-12-28 16:46:40,409:DEBUG:acme.client:Storing nonce: LPSR-4-REMOVED-REMOVED
2024-12-28 16:46:40,409:DEBUG:acme.client:JWS payload:
b'{\n  "identifiers": [\n    {\n      "type": "dns",\n      "value": "*.example.com"\n    }\n  ]\n}'
2024-12-28 16:46:40,411:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/new-order:
{
  "protected": "REMOVED",
  "signature": "REMOVED",
  "payload": "REMOVED"
}
2024-12-28 16:46:40,500:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/new-order HTTP/11" 201 347
2024-12-28 16:46:40,501:DEBUG:acme.client:Received response:
HTTP 201
Server: nginx
Date: Sat, 28 Dec 2024 16:46:40 GMT
Content-Type: application/json
Content-Length: 347
Connection: keep-alive
Boulder-Requester: 2137809385
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Location: https://acme-v02.api.letsencrypt.org/acme/order/REMOVED/REMOVED
Replay-Nonce: REMOVED-REMOVED
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "status": "pending",
  "expires": "2025-01-04T03:29:07Z",
  "identifiers": [
    {
      "type": "dns",
      "value": "*.example.com"
    }
  ],
  "authorizations": [
    "https://acme-v02.api.letsencrypt.org/acme/authz/REMOVED/REMOVED"
  ],
  "finalize": "https://acme-v02.api.letsencrypt.org/acme/finalize/REMOVED/REMOVED"
}
2024-12-28 16:46:40,501:DEBUG:acme.client:Storing nonce: REMOVED-REMOVED
2024-12-28 16:46:40,502:DEBUG:acme.client:JWS payload:
b''
2024-12-28 16:46:40,504:DEBUG:acme.client:Sending POST request to https://acme-v02.api.letsencrypt.org/acme/authz/REMOVED/REMOVED:
{
  "protected": "REMOVED",
  "signature": "REMOVED-REMOVED-REMOVED-REMOVED",
  "payload": ""
}
2024-12-28 16:46:40,549:DEBUG:urllib3.connectionpool:https://acme-v02.api.letsencrypt.org:443 "POST /acme/authz/REMOVED/REMOVED HTTP/11" 200 393
2024-12-28 16:46:40,549:DEBUG:acme.client:Received response:
HTTP 200
Server: nginx
Date: Sat, 28 Dec 2024 16:46:40 GMT
Content-Type: application/json
Content-Length: 393
Connection: keep-alive
Boulder-Requester: 2137809385
Cache-Control: public, max-age=0, no-cache
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: LPSR-4-REMOVED
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800

{
  "identifier": {
    "type": "dns",
    "value": "example.com"
  },
  "status": "pending",
  "expires": "2025-01-04T03:29:07Z",
  "challenges": [
    {
      "type": "dns-01",
      "url": "https://acme-v02.api.letsencrypt.org/acme/chall/REMOVED/REMOVED/REMOVED",
      "status": "pending",
      "token": "REMOVED"
    }
  ],
  "wildcard": true
}
2024-12-28 16:46:40,550:DEBUG:acme.client:Storing nonce: LPSR-4-REMOVED
2024-12-28 16:46:40,550:INFO:certbot._internal.auth_handler:Performing the following challenges:
2024-12-28 16:46:40,550:INFO:certbot._internal.auth_handler:dns-01 challenge for example.com
2024-12-28 16:46:40,564:DEBUG:filelock:Attempting to acquire lock 281473647166528 on /root/.cache/python-tldextract/3.13.0.final__venv__63d330__tldextract-5.1.3/publicsuffix.org-tlds/REMOVED.tldextract.json.lock
2024-12-28 16:46:40,564:DEBUG:filelock:Lock 281473647166528 acquired on /root/.cache/python-tldextract/3.13.0.final__venv__63d330__tldextract-5.1.3/publicsuffix.org-tlds/REMOVED.tldextract.json.lock
2024-12-28 16:46:40,565:DEBUG:filelock:Attempting to acquire lock 281473647637392 on /root/.cache/python-tldextract/3.13.0.final__venv__63d330__tldextract-5.1.3/urls/REMOVED.tldextract.json.lock
2024-12-28 16:46:40,565:DEBUG:filelock:Lock 281473647637392 acquired on /root/.cache/python-tldextract/3.13.0.final__venv__63d330__tldextract-5.1.3/urls/REMOVED.tldextract.json.lock
2024-12-28 16:46:40,566:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): publicsuffix.org:443
2024-12-28 16:46:40,643:DEBUG:urllib3.connectionpool:https://publicsuffix.org:443 "GET /list/public_suffix_list.dat HTTP/11" 200 86474
2024-12-28 16:46:40,711:DEBUG:filelock:Attempting to release lock 281473647637392 on /root/.cache/python-tldextract/3.13.0.final__venv__63d330__tldextract-5.1.3/urls/REMOVED.tldextract.json.lock
2024-12-28 16:46:40,711:DEBUG:filelock:Lock 281473647637392 released on /root/.cache/python-tldextract/3.13.0.final__venv__63d330__tldextract-5.1.3/urls/REMOVED.tldextract.json.lock
2024-12-28 16:46:40,723:DEBUG:filelock:Attempting to release lock 281473647166528 on /root/.cache/python-tldextract/3.13.0.final__venv__63d330__tldextract-5.1.3/publicsuffix.org-tlds/REMOVED.tldextract.json.lock
2024-12-28 16:46:40,723:DEBUG:filelock:Lock 281473647166528 released on /root/.cache/python-tldextract/3.13.0.final__venv__63d330__tldextract-5.1.3/publicsuffix.org-tlds/REMOVED.tldextract.json.lock
2024-12-28 16:46:40,744:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.porkbun.com:443
2024-12-28 16:46:41,669:DEBUG:urllib3.connectionpool:https://api.porkbun.com:443 "POST /api/json/v3/dns/create/example.com HTTP/11" 400 None
2024-12-28 16:46:41,678:DEBUG:certbot._internal.error_handler:Encountered exception:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.13/site-packages/certbot_dns_porkbun/cert/client.py", line 117, in _perform
    client.create_dns_record(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        root_domain, DNSRecordType.TXT, validation, name=name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/opt/venv/lib/python3.13/site-packages/pkb_client/client/client.py", line 141, in create_dns_record
    raise PKBClientException(
    ...<2 lines>...
    )
pkb_client.client.client.PKBClientException: ERROR: Create error: We were unable to create the DNS record.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.13/site-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/opt/venv/lib/python3.13/site-packages/certbot/plugins/dns_common.py", line 80, in perform
    self._perform(domain, validation_domain_name, validation)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.13/site-packages/certbot_dns_porkbun/cert/client.py", line 124, in _perform
    raise errors.PluginError(e)
certbot.errors.PluginError: ERROR: Create error: We were unable to create the DNS record.

2024-12-28 16:46:41,678:DEBUG:certbot._internal.error_handler:Calling registered functions
2024-12-28 16:46:41,678:INFO:certbot._internal.auth_handler:Cleaning up challenges
2024-12-28 16:46:41,679:ERROR:certbot._internal.error_handler:Encountered exception during recovery: KeyError: 'Github issue note: The value in this string was on one of the TXT acme-challenge entries'
2024-12-28 16:46:41,679:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.13/site-packages/certbot_dns_porkbun/cert/client.py", line 117, in _perform
    client.create_dns_record(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        root_domain, DNSRecordType.TXT, validation, name=name
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "/opt/venv/lib/python3.13/site-packages/pkb_client/client/client.py", line 141, in create_dns_record
    raise PKBClientException(
    ...<2 lines>...
    )
pkb_client.client.client.PKBClientException: ERROR: Create error: We were unable to create the DNS record.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/bin/certbot", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/venv/lib/python3.13/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/opt/venv/lib/python3.13/site-packages/certbot/_internal/main.py", line 1876, in main
    return config.func(config, plugins)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.13/site-packages/certbot/_internal/main.py", line 1578, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/opt/venv/lib/python3.13/site-packages/certbot/_internal/main.py", line 142, in _get_and_save_cert
    lineage = le_client.obtain_and_enroll_certificate(domains, certname)
  File "/opt/venv/lib/python3.13/site-packages/certbot/_internal/client.py", line 517, in obtain_and_enroll_certificate
    cert, chain, key, _ = self.obtain_certificate(domains)
                          ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/venv/lib/python3.13/site-packages/certbot/_internal/client.py", line 428, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/opt/venv/lib/python3.13/site-packages/certbot/_internal/client.py", line 496, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
  File "/opt/venv/lib/python3.13/site-packages/certbot/_internal/auth_handler.py", line 88, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/opt/venv/lib/python3.13/site-packages/certbot/plugins/dns_common.py", line 80, in perform
    self._perform(domain, validation_domain_name, validation)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.13/site-packages/certbot_dns_porkbun/cert/client.py", line 124, in _perform
    raise errors.PluginError(e)
certbot.errors.PluginError: ERROR: Create error: We were unable to create the DNS record.
2024-12-28 16:46:41,683:ERROR:certbot._internal.log:ERROR: Create error: We were unable to create the DNS record.
```

### Command

```shell
certbot certonly 
    -v 
    --non-interactive 
    --agree-tos 
    --email $MY_VALID_PORKBUN_EMAIL 
    --preferred-challenges dns 
    --authenticator dns-porkbun 
    --dns-porkbun-key $PORKBUN_API_KEY 
    --dns-porkbun-secret $PORKBUN_SECRET_KEY 
    --dns-porkbun-propagation-seconds 600 
    -d "*.example.com"
```

### Steps to reproduce

Run the command above when there are two or more TXT records at Porkbun for the acme challenge.  I am not sure how I created this corner case condition - it was through several failed attempts at running certbot.

### Checklist

- [X] I have checked for [existing Github issues](https://github.com/infinityofspace/certbot_dns_porkbun/issues) for the same bug.
- [X] I have checked to see if there is a [newer version](https://github.com/infinityofspace/certbot_dns_porkbun/releases) that already fixes this error.

**Comment by smclewin** [comment]
I think I see how I got things into this state.  If I run the command with a 600 second propagation delay and stop/kill the command before the 600 seconds is completed the TXT record appears to be getting left in the Porkbun DNS entry.  I think that is how I ended up with four acme challenge TXT entries for my domain.

**Comment by tggjifdhn** [comment]
I'm experiencing this issue as well.

**Comment by infinityofspace** [comment]
Thanks for the bug report, I was able to recreate the problem with existing dns challenge records.
The initial situation with several DNS challenge records is due to the fact that they have not been cleaned up in your case. Maybe the certbot process was stopped before the automatic cleanup in case of an abort. When stopping an active DNS challenge, the certbot process should be given some time for the cleanup process to finish. Unfortunately, I could not reproduce the problem where multiple records are created.

The actual problem for a new challenge with one or more existing DNS challenge records is due to the clean-up process logic. This requires a previous creation of the records in the same plugin execution. However, this is of course problematic if a previous DNS challenge was not successful for whatever reason and is reused.
I will try to implement a bugfix in the next version for this issue. So you should be able to create a new dns challenge when there are unfinished dns challenge records.

**Comment by smclewin** [comment]
Great, thank you for your time and work @infinityofspace. 

In my case the certbot container was stopped due to an abort while I was getting everything set up initially.  This has never happened under normal operations.  I forget what I missed, but the end result is that the container would start, begin the process and then "hang" (probably not an actual lockup, but it was stuck waiting on something that would never happen) and I would tear down the Docker container, iterate, and try again.

Once I spotted the multiple DNS challenge records at Porkbun I deleted them and things worked great.
